### ISSUE TITLE
Crash on multiplayer connect

### ISSUE THREAD

**Issue by MrAlexand0r** [bobsgame/bobsgame#1]
When trying to play multiplayer the game just stops responding. I let it load for several minutes but it doesnt seem to do something.

![image](https://user-images.githubusercontent.com/18336077/28974161-b7d43bb4-7935-11e7-93ad-dd3cc668c86a.png)

**Comment by robertpelloni** [comment]
Thank you for reporting this.  Please try it again with today's build.
